### ISSUE TITLE
Initial Values for the quaternion in rbcar_robot_control.cpp

### ISSUE THREAD

**Issue by ParitoshKelkar** [RobotnikAutomation/rbcar_sim#4]
Hi, 

I was trying to run the robot_control_node from the gazebo launch files to generate odometry data. I was however getting tf errors - the odometry message had a few nan values. 
I traced this back to the initialization of the quaternion in rbcar_robot_control.cpp(line 258)- all elements of the quaternion are initialized to 0. This is causing a generation of 'nan' and it then percolates through the code.  It probably should be initialized with the real part of the quaternion set to 1. 

`  // Imu variables
  ang_vel_x_ = 0.0; ang_vel_y_ = 0.0; ang_vel_z_ = 0.0;
  lin_acc_x_ = 0.0; lin_acc_y_ = 0.0; lin_acc_z_ = 0.0;

  orientation_x_ = 0.0; orientation_y_ = 0.0; orientation_z_ = 0.0; orientation_w_ = 0.0;

  // Advertise controller services
  srv_SetOdometry_ = rbcar_robot_control_node_handle.advertiseService("set_odometry",  &RbcarControllerClass::srvCallback_SetOdometry, this);
`

Is there a mistake with the way I run the node? Is there any other way of obtaining  odomtery data? I needed odometry data for amcl and other move_base packages ,. 
Please let me know! 

Thanks!

**Comment by rguzman1** [comment]
Hi!

you are right, the quaternion is wrongly initialized. In addition there is
some noise in the joint position that is integrated leading to a growing
odometry error, even with the robot stopped.

I will try to fix this week.

   Thanks and best regards,

       Roberto


El 9 mar. 2017 23:05, "Paritosh Kelkar" <notifications@github.com> escribió:

Hi,

I was trying to run the robot_control_node from the gazebo launch files to
generate odometry data. I was however getting tf errors - the odometry
message had a few nan values.
I traced this back to the initialization of the quaternion in
rbcar_robot_control.cpp(line 258)- all elements of the quaternion are
initialized to 0. This is causing a generation of 'nan' and it then
percolates through the code. It probably should be initialized with the
real part of the quaternion set to 1.

` // Imu variables
ang_vel_x_ = 0.0; ang_vel_y_ = 0.0; ang_vel_z_ = 0.0;
lin_acc_x_ = 0.0; lin_acc_y_ = 0.0; lin_acc_z_ = 0.0;

orientation_x_ = 0.0; orientation_y_ = 0.0; orientation_z_ = 0.0;
orientation_w_ = 0.0;

// Advertise controller services
srv_SetOdometry_ =
rbcar_robot_control_node_handle.advertiseService("set_odometry",
&RbcarControllerClass::srvCallback_SetOdometry, this);
`

Is there a mistake with the way I run the node? Is there any other way of
obtaining odomtery data? I needed odometry data for amcl and other
move_base packages ,.
Please let me know!

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RobotnikAutomation/rbcar_sim/issues/4>, or mute the
thread

**Comment by RomanRobotnik** [comment]
I think the problem is solved with this [commit](https://github.com/RobotnikAutomation/rbcar_sim/commit/cc089158e68cf75b46468afd360b395afd24d6a8)
